-- ============================================================
--  V9 – AI Explanation & Trigger Details for Observations
--
--  Adds two columns to observation_list so the ThreatDetectionService
--  can persist:
--    1. details        – the human-readable trigger message that was
--                        previously only written to the application log.
--    2. ai_explanation – the natural-language analysis generated by the
--                        local Ollama LLM after an observation is flagged.
--                        Populated asynchronously; may be NULL while the
--                        LLM call is in-flight or if Ollama is unavailable.
-- ============================================================

ALTER TABLE observation_list
    ADD COLUMN IF NOT EXISTS details        TEXT,
    ADD COLUMN IF NOT EXISTS ai_explanation TEXT;
